# Human-readable module metadata.
# ABK reads this file to validate and prefill module options.

ABK_MODULE_NAME="fix 8gen3 gunyah"
ABK_MODULE_VERSION="0.1"
ABK_MODULE_DESCRIPTION="fix 8gen3 gunyun,only support kernel version 6.1.162 and above"
ABK_MODULE_SUPPORTED_STAGES="after_patch,before_build"
ABK_MODULE_DEFAULT_STAGE="after_patch"
ABK_MODULE_RECOMMENDED_STAGES="after_patch,before_build"
